import {useEffect,useState} from 'react';
import {api} from '../api/client';
export default function ActivationInsights(){
  const [data,setData]=useState(null),[failed,setFailed]=useState(false);
  useEffect(()=>{let active=true;api.activationInsights().then(d=>{if(active)setData(d);}).catch(()=>{if(active)setFailed(true);});return()=>{active=false;};},[]);
  const rate=(count,total)=>total?`${Math.round(100*count/total)}% (${count}/${total})`:'Not enough elapsed days yet';
  return <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="font-bold">Building a care history</h2><p className="mt-2 text-sm text-slate-500">New accounts since rollout, opted-in participants only. Aggregate figures; no names or care details. Return days are calendar days after the first entry, using the account’s initial timezone. Figures cover the rollout to date.</p>
    {data?<><p className="mt-3 text-sm">All new accounts: <strong>{data.accounts}</strong> · With a care profile: <strong>{data.accounts_with_profile}</strong>. These two totals use existing account records; the funnel below covers opted-in participants.</p><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Participating accounts',data.participants],['Created a profile',data.person],['First entry',data.first],['Three entries',data.three],['Used a report',data.reports],['Shared a report',data.shares],['Recorded paid conversion',data.paid]].map(([label,value])=><div key={label} className="rounded-xl bg-slate-50 p-3"><strong className="text-xl">{value}</strong><p className="text-xs">{label}</p></div>)}</div><p className="mt-4 font-semibold">Next-day return: {rate(data.day2,data.day2_eligible)}</p><p className="mt-2 text-sm">Day-three return: {rate(data.day3,data.day3_eligible)}</p><p className="mt-2 text-xs text-slate-500">Return rates include only accounts opted in by their first-entry day and old enough for the relevant return day. Entry milestones reflect current undeleted records. Paid conversion means a positive payment recorded after joining guidance, not simply starting a trial.</p></>:<p className="mt-3 text-sm">{failed?'Activation statistics are temporarily unavailable.':'Loading activation statistics…'}</p>}
  </section>;
}
