import { useEffect, useState } from 'react';
import { api } from '../api/client';
const field='w-full rounded-xl border border-slate-200 bg-white p-3 text-sm';
const button='rounded-xl bg-indigo-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-50';
export default function AdminEmail({initial={}}) {
 const [users,setUsers]=useState([]),[messages,setMessages]=useState([]),[settings,setSettings]=useState({});
 const [selected,setSelected]=useState([]),[search,setSearch]=useState(''),[subject,setSubject]=useState(''),[text,setText]=useState('');
 const [preview,setPreview]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [folder,setFolder]=useState('compose');
 const load=async()=>{const data=await api.adminEmails();setMessages(data.messages);setSettings(data.settings);};
 useEffect(()=>{let stopped=false;Promise.all([api.adminEmailRecipients(),api.adminEmails()]).then(([u,d])=>{if(stopped)return;setUsers(u);setMessages(d.messages);setSettings(d.settings);setSelected(u.filter(x=>x.id===initial.userId || x.families.some(f=>f.id===initial.familyId)).map(x=>x.id));}).catch(e=>setError(e.message));return()=>{stopped=true;};},[initial.userId,initial.familyId]);
 const run=async fn=>{setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const save=()=>run(async()=>{const d=await api.adminEmailCreate({subject,text,userIds:selected});setPreview(await api.adminEmailDetail(d.id));await load();setNotice('Draft saved. Check the recipients and preview before sending.');});
 const open=id=>run(async()=>{setPreview(await api.adminEmailDetail(id));setFolder('compose');});
 const send=()=>run(async()=>{
 if(!window.confirm(`Send “${preview.subject}” to ${preview.recipients.filter(r=>r.status==='pending').length} recipients? Each person receives a private individual email.`))return;
 let pending=1;while(pending){const result=await api.adminEmailSend(preview.id);pending=result.pending;setNotice(`Sending: ${result.counts.map(c=>`${c.count} ${c.status}`).join(', ')}`);}
 setPreview(await api.adminEmailDetail(preview.id));await load();setNotice('Send attempt finished. Check each recipient’s status below.');
 });
 const reset=()=>{setPreview(null);setSubject('');setText('');setSelected([]);setFolder('compose');setNotice('');};
 const visible=users.filter(u=>`${u.name} ${u.email} ${u.families.map(f=>f.name).join(' ')}`.toLowerCase().includes(search.toLowerCase()));
 return <section className="mt-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
 <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black text-slate-900">FamilyTrack Email</h2><p className="text-sm text-slate-500">Service updates and personal support, sent from your admin account.</p></div><button disabled={busy} className={button} onClick={reset}>New email</button></div>
 <div className="my-4 flex gap-2">{['compose','drafts','history'].map(f=><button disabled={busy} key={f} onClick={()=>setFolder(f)} className={`rounded-lg px-3 py-2 capitalize ${folder===f?'bg-indigo-100 font-bold text-indigo-800':'bg-slate-50'}`}>{f}</button>)}</div>
 {error&&<p role="alert" className="my-3 rounded-xl bg-rose-50 p-3 text-rose-800">{error}</p>}{notice&&<p role="status" className="my-3 rounded-xl bg-sky-50 p-3 text-sky-800">{notice}</p>}
 {folder!=='compose'?<div className="space-y-2">{messages.filter(m=>folder==='drafts'?m.status==='draft':m.status!=='draft').map(m=><button key={m.id} disabled={busy} onClick={()=>open(m.id)} className="block w-full rounded-xl border border-slate-200 p-3 text-left"><strong>{m.subject}</strong><p className="text-xs text-slate-500">{m.recipients} recipients · {m.status} · {new Date(m.created_at).toLocaleString()} · {m.author}</p></button>)}{!messages.some(m=>folder==='drafts'?m.status==='draft':m.status!=='draft')&&<p>No emails here yet.</p>}</div>:
 preview?<div className="space-y-4"><p className="text-sm">From: <strong>{preview.settings.from}</strong><br/>Replies: {preview.settings.replyTo}</p><h3 className="font-bold">{preview.recipients.length} recipients</h3><div className="max-h-48 overflow-auto rounded-xl border p-3 text-sm">{preview.recipients.map(r=><p key={r.user_id}>{r.name} &lt;{r.email}&gt; — {r.status==='sent'?'Sent (provider accepted)':r.status==='sending'?'Sending / awaiting confirmation':r.status}</p>)}</div>
 <iframe title="Branded email preview" sandbox="" srcDoc={preview.html} className="h-[520px] w-full rounded-xl border"/>
 <p className="text-xs text-slate-500">Keep this page open while sending; unfinished recipients can be resumed from History. Replies go to the mailbox above. This page does not receive incoming mail. Uncertain deliveries are not automatically retried.</p>
 {preview.recipients.some(r=>r.status==='pending')&&<button className={button} disabled={busy||!settings.ready} onClick={send}>{busy?'Sending…':`Send to ${preview.recipients.filter(r=>r.status==='pending').length} recipients`}</button>}
 {!settings.ready&&<p className="text-amber-800">Sending is unavailable until the hello@familytrack.care sender and email provider are configured.</p>}
 {preview.status==='draft'&&<button disabled={busy} className="ml-3 rounded-xl border px-4 py-2" onClick={()=>{setSubject(preview.subject);setText(preview.body);setSelected(preview.recipients.map(r=>r.user_id));setPreview(null);}}>Edit as new draft</button>}
 </div>:<div className="grid gap-5 lg:grid-cols-[minmax(240px,1fr)_2fr]"><div><h3 className="font-bold">Recipients · {selected.length} selected</h3><p className="my-2 text-xs text-slate-500">Active accounts means non-deleted, non-suspended users, including trial accounts. Addresses are never shared with other recipients.</p><input aria-label="Search recipients" placeholder="Search name, email or family" className={field} value={search} onChange={e=>setSearch(e.target.value)}/><div className="my-2 flex flex-wrap gap-2"><button className="rounded-lg bg-indigo-50 p-2 text-sm" onClick={()=>setSelected(users.map(u=>u.id))}>Select all active users ({users.length})</button><button className="p-2 text-sm" onClick={()=>setSelected([])}>Clear</button></div><div className="max-h-80 overflow-auto rounded-xl border">{visible.map(u=><label key={u.id} className="flex gap-2 border-b p-3 text-sm"><input type="checkbox" checked={selected.includes(u.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,u.id]:s.filter(id=>id!==u.id))}/><span><strong>{u.name||u.email}</strong><span className="block break-all text-xs text-slate-500">{u.email}</span></span></label>)}</div></div>
 <div className="space-y-3"><p className="text-sm text-slate-500">From: {settings.from}<br/>Reply to: {settings.replyTo}</p><label className="block text-sm font-bold">Subject<input className={field} maxLength={160} value={subject} onChange={e=>setSubject(e.target.value)}/></label><label className="block text-sm font-bold">Message<textarea className={field} rows={12} maxLength={20000} value={text} onChange={e=>setText(e.target.value)} placeholder="Write your message. FamilyTrack branding is added automatically."/></label><button className={button} disabled={busy||!selected.length||!subject.trim()||!text.trim()} onClick={save}>{busy?'Saving…':'Save draft & preview'}</button><p className="text-xs text-slate-500">No email is sent until you confirm from the preview.</p></div></div>}
 </section>;
}
