import {useEffect,useState} from 'react';
import {attendanceLabels} from '../attendance';
import {localDay,attendanceState} from '../attendanceCalendar';
const colours={neutral:'border-slate-200 bg-white text-slate-600',active:'border-sky-300 bg-sky-50 text-sky-900',present:'border-emerald-300 bg-emerald-50 text-emerald-900',absent:'border-rose-300 bg-rose-50 text-rose-900',partial:'border-amber-300 bg-amber-50 text-amber-900',closed:'border-purple-300 bg-purple-50 text-purple-900'};
const names={neutral:'Not recorded',active:'At school',present:'Present',absent:'Absent',partial:'Part-day',closed:'Holiday / closure'};
export default function AttendanceCalendar({settings={},loadMonth,onSave,canAdd,canEdit,refreshKey}){
 const [month,setMonth]=useState(()=>localDay().slice(0,7)),[entries,setEntries]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState(null),[editingEntry,setEditingEntry]=useState(null),[status,setStatus]=useState('attended'),[notes,setNotes]=useState(''),[busy,setBusy]=useState(false),[version,setVersion]=useState(0);
 const [year,number]=month.split('-').map(Number),count=new Date(year,number,0).getDate(),offset=(new Date(year,number-1,1).getDay()+6)%7,today=localDay();
 useEffect(()=>{let cancelled=false;setLoading(true);setError('');loadMonth(month+'-01',`${month}-${count}`).then(rows=>{if(!cancelled)setEntries(rows);}).catch(e=>{if(!cancelled)setError(e.message||'Could not load attendance.');}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[month,refreshKey,version]);
 const byDay=new Map(entries.map(e=>[e.rawLogDate,e]));const current=editingEntry,active=attendanceState(current,selected,today)==='active',allowed=current?canEdit:canAdd;
 const changeMonth=n=>{setMonth(localDay(new Date(year,number-1+n,1)).slice(0,7));setSelected(null);};
 return <section className="mt-5 rounded-2xl border border-slate-200 bg-white p-3 sm:p-5"><div className="flex items-center justify-between gap-2"><button type="button" aria-label="Previous month" className="rounded-xl border px-3 py-2" onClick={()=>changeMonth(-1)}>‹</button><h3 className="font-bold">{new Date(year,number-1,1).toLocaleDateString('en-GB',{month:'long',year:'numeric'})}</h3><button type="button" aria-label="Next month" className="rounded-xl border px-3 py-2" onClick={()=>changeMonth(1)}>›</button></div><div className="mt-3 flex flex-wrap gap-2 text-xs">{['present','absent','partial','closed'].map(k=><span key={k} className={`rounded-lg border px-2 py-1 ${colours[k]}`}>{names[k]}</span>)}</div><p className="my-3 text-xs text-slate-500">Tap a date to update its status or add a note. Saved days use their category colour, including future plans. Empty dates stay neutral.</p>{error&&<p role="alert" className="my-2 text-sm text-rose-700">{error}</p>}
 <div className="grid grid-cols-7 gap-1" aria-label="School attendance calendar">{['M','T','W','T','F','S','S'].map((d,i)=><div key={'h'+i} className="py-1 text-center text-xs font-bold text-slate-500">{d}</div>)}{Array.from({length:offset},(_,i)=><div key={'blank'+i}/>)}{Array.from({length:count},(_,i)=>{const day=`${month}-${String(i+1).padStart(2,'0')}`,entry=byDay.get(day),state=attendanceState(entry,day,today);return <button type="button" key={day} disabled={loading||busy||!!error} aria-label={`${day}: ${entry?names[state]:day>today?'Future':names[state]}${entry?', '+attendanceLabels[entry.rawData.attendanceStatus]:''}`} aria-pressed={selected===day} onClick={()=>{setSelected(day);setEditingEntry(entry||null);setStatus(entry?.rawData.attendanceStatus||'attended');setNotes(entry?.rawNotes||'');}} className={`min-h-12 min-w-0 rounded-xl border text-sm font-semibold ${colours[state]} ${selected===day?'ring-2 ring-indigo-500':''} ${day===today?'font-extrabold underline':''} disabled:opacity-50`}>{i+1}{state==='active'&&<span className="block text-[9px]">Away</span>}</button>})}</div>{loading&&<p role="status" className="mt-3 text-sm">Loading attendance…</p>}
 {selected&&!loading&&<div className="mt-4 rounded-xl bg-slate-50 p-4"><h4 className="font-bold">{new Date(selected+'T12:00:00').toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'})}</h4>{active&&<p className="mt-2 text-sm text-sky-800">School is still active. Use Picked Up/Home above to finish normally. Changing this day to an absence, holiday or part-day will clear the active school state.</p>}<fieldset disabled={!allowed||busy} className="mt-3 space-y-3"><label className="block text-sm font-semibold">Status<select className="mt-1 w-full rounded-xl border bg-white p-3" value={status} onChange={e=>setStatus(e.target.value)}>{Object.entries(attendanceLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="block text-sm font-semibold">Note (optional)<textarea className="mt-1 w-full rounded-xl border bg-white p-3" rows={2} value={notes} onChange={e=>setNotes(e.target.value)}/></label>{allowed&&<button type="button" className="rounded-xl bg-indigo-700 px-4 py-3 font-bold text-white disabled:opacity-50" disabled={busy} onClick={async()=>{if(busy)return;setBusy(true);setError('');try{await onSave(current,{startDate:selected,endDate:selected,data:{...(current?.rawData||{}),attendance:true,attendanceStatus:status,partDay:status==='part_day'||(status==='medical'&&current?.rawData.partDay===true),setting:current?.rawData.setting||settings.name||''},notes});setSelected(null);setVersion(v=>v+1);}catch(e){setError(e.message||'Could not save attendance.');}finally{setBusy(false);}}}>{busy?'Saving…':'Save day'}</button>}</fieldset>{!allowed&&<p className="mt-2 text-sm text-slate-500">Your access does not allow changes to this day.</p>}</div>}
 </section>;
}
