import AttendanceForm from './AttendanceForm';
import FeedForm from './FeedForm';
import {useState} from 'react';
const field='mt-1 w-full rounded-xl border border-slate-300 bg-white p-3';
export default function CareEntryEditor({entry,profiles,onClose,onSave}) {
 const [mode,setMode]=useState('edit'),[date,setDate]=useState(entry.rawLogDate),[time,setTime]=useState(entry.time||''),[data,setData]=useState({...entry.rawData}),[notes,setNotes]=useState(entry.rawNotes||''),[target,setTarget]=useState(entry.childId),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const save=async action=>{if(action==='delete'&&!window.confirm('Delete this entry? You can undo it for 15 minutes.'))return;setBusy(true);setError('');try{await onSave(action,{logDate:date,logTime:time,data,notes,childId:target});onClose();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const editable=['route','item','amount','unit','description','intake_status','location','name','medication','dose','dose_amount','dose_unit','given_by','status','entry','quality','bedtime','wake_time','wake_date','nap','type','severity','duration','title','professional','outcome','weight','height','temperature','value','medicine','behaviour_type','recovery_time','what_helped','event','weight_kg','height_cm','night_wakings'];
 const labels={item:'Food / drink',intake_status:'Intake',given_by:'Given by',wake_time:'Wake-up time',wake_date:'Wake-up date',bedtime:'Sleep start time',dose_amount:'Dose amount',dose_unit:'Dose unit'};
 return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/50 p-3" role="dialog" aria-modal="true" aria-label="Change saved entry"><div className="max-h-[90vh] w-full max-w-xl overflow-auto rounded-2xl bg-white p-5 shadow-xl"><div className="flex justify-between gap-3"><h2 className="text-xl font-bold">Change saved entry</h2><button type="button" disabled={busy} onClick={onClose}>Close</button></div><p className="my-2 text-sm text-slate-600">{entry.summary}</p><div className="flex flex-wrap gap-2">{['edit','move'].map(m=><button type="button" disabled={busy} key={m} onClick={()=>setMode(m)} className={`rounded-xl px-4 py-2 ${mode===m?'bg-indigo-600 text-white':'bg-slate-100'}`}>{m==='edit'?'Edit entry':'Move to another profile'}</button>)}</div>{error&&<p role="alert" className="my-3 text-rose-700">{error}</p>}
 <fieldset disabled={busy} className="mt-4 space-y-3">
 {mode==='edit' && entry.rawData?.attendance ? <AttendanceForm entry={entry} onSave={async p=>{await onSave('edit',{logDate:p.startDate,logTime:p.data.arrival||'',data:p.data,notes:p.notes});onClose();}}/> : mode==='edit' && entry.rawData?.feeding ? <FeedForm entry={entry} onSave={async(d,n)=>{await onSave('edit',{logDate:d.feed_start.slice(0,10),logTime:d.feed_start.slice(11,16),data:d,notes:n});onClose();}}/> : mode==='move'?<label className="block text-sm font-bold">Move to<select className={field} value={target} onChange={e=>setTarget(e.target.value)}>{profiles.map(p=><option key={p.id} value={p.id}>{p.firstName||p.name||'Care profile'}</option>)}</select><span className="mt-2 block font-normal">Moves this saved entry and its details. It does not create a copy.</span></label>:<><div className="grid grid-cols-2 gap-3"><label>Date<input type="date" className={field} value={date} onChange={e=>setDate(e.target.value)}/></label><label>Time<input type="time" className={field} value={time} onChange={e=>setTime(e.target.value)}/></label></div>{Object.entries(data).filter(([k,v])=>editable.includes(k)&&['string','number','boolean'].includes(typeof v)).map(([k,v])=><label key={k} className="block text-sm capitalize">{labels[k]||k.replaceAll('_',' ')}{typeof v==='boolean'?<input type="checkbox" checked={v} onChange={e=>setData(d=>({...d,[k]:e.target.checked}))}/>:<input className={field} type={typeof v==='number'?'number':k==='bedtime'||k==='wake_time'?'time':k==='wake_date'?'date':'text'} step="any" value={v} onChange={e=>{const value=e.target.value;setData(d=>({...d,[k]:typeof v==='number'?Number(value):value}));}}/>}</label>)}<label className="block">Notes<textarea className={field} rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></label></>}
 <div className="flex flex-wrap justify-between gap-3 border-t pt-4">
 <button type="button" className="rounded-xl border border-rose-200 px-4 py-3 text-rose-700" onClick={()=>save('delete')}>Delete entry</button>
 {!(mode==='edit' && (entry.rawData?.feeding || entry.rawData?.attendance)) && <button type="button" disabled={mode==='move'?target===entry.childId:!date} className="rounded-xl bg-indigo-600 px-4 py-3 font-bold text-white disabled:opacity-50" onClick={()=>save(mode)}>{busy?'Saving…':mode==='move'?'Move entry':'Save changes'}</button>}
 </div></fieldset></div></div>;
}
