import {useState} from 'react';
export function orderedTileIds(saved,available){return [...new Set([...(Array.isArray(saved)?saved:[]).filter(id=>available.includes(id)),...available])];}
export default function DashboardLayout({items,storageKey}){
 const [saved,setSaved]=useState(()=>{try{return JSON.parse(localStorage.getItem(storageKey)||'[]');}catch{return [];}}),[editing,setEditing]=useState(false),[notice,setNotice]=useState('');
 const visible=items.filter(item=>item.content),ids=orderedTileIds(saved,visible.map(item=>item.id)),byId=new Map(visible.map(item=>[item.id,item]));
 const persist=next=>{setSaved(next);try{localStorage.setItem(storageKey,JSON.stringify(next));setNotice('Order saved on this device.');}catch{setNotice('Order changed for now. This device could not save it.');}};
 const move=(id,to)=>{const next=[...ids],from=next.indexOf(id);if(from<0||to<0||to>=next.length)return;next.splice(from,1);next.splice(to,0,id);const hidden=(Array.isArray(saved)?saved:[]).filter(k=>!ids.includes(k));persist([...next,...hidden]);};
 return <><div className="mb-3 flex items-center justify-between gap-3"><h2 className="text-sm font-bold text-slate-700">Your dashboard</h2><button type="button" onClick={()=>{setEditing(!editing);setNotice('');}} aria-expanded={editing} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-bold text-indigo-700">{editing?'Done':'Arrange tiles'}</button></div>
 {editing&&<section aria-label="Arrange dashboard tiles" className="mb-4 rounded-2xl border border-indigo-100 bg-indigo-50 p-3"><p className="mb-3 text-sm text-slate-600">Move tiles up or down, or choose any position. Saved for this profile on this device.</p><ol className="space-y-2">{ids.map((id,index)=><li key={id} className="flex min-w-0 items-center gap-2 rounded-xl bg-white p-2"><span className="min-w-0 flex-1 text-sm font-semibold">{byId.get(id).label}</span><select aria-label={`Position of ${byId.get(id).label}`} className="rounded-lg border p-2 text-sm" value={index} onChange={e=>move(id,Number(e.target.value))}>{ids.map((_,i)=><option key={i} value={i}>{i+1}</option>)}</select><button type="button" aria-label={`Move ${byId.get(id).label} up`} disabled={index===0} onClick={()=>move(id,index-1)} className="rounded-lg border px-3 py-2 disabled:opacity-30">↑</button><button type="button" aria-label={`Move ${byId.get(id).label} down`} disabled={index===ids.length-1} onClick={()=>move(id,index+1)} className="rounded-lg border px-3 py-2 disabled:opacity-30">↓</button></li>)}</ol><div className="mt-3 flex items-center justify-between gap-2"><button type="button" className="text-sm font-semibold underline" onClick={()=>persist([])}>Reset order</button><button type="button" className="rounded-xl bg-indigo-700 px-4 py-2 font-bold text-white" onClick={()=>setEditing(false)}>Done</button></div></section>}
 <p role="status" className="sr-only">{notice}</p><div className="grid grid-cols-2 gap-2.5 lg:grid-cols-3">{ids.map(id=><div key={id} className={`min-w-0 ${byId.get(id).wide?'col-span-2 lg:col-span-3':''}`}>{byId.get(id).content}</div>)}</div></>;
}
