import {useState,useRef} from 'react';
import {normaliseFeed,routeLabels} from '../feeding';
const field='mt-1 block w-full min-w-0 rounded-xl border border-slate-300 bg-white p-3 text-base';
const localNow=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}T${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;};
export default function FeedForm({settings={},entry,onSave,onCancel,canStart=false,presets=[]}) {
 const [data,setData]=useState(()=>entry?{...entry.rawData}:{feeding:true,item:'',feed_route:settings.route==='combination'?(settings.routes||[])[0]||'ng':settings.route||'ng',feed_method:'bolus',feed_planned_ml:'',feed_given_ml:'',feed_rate:'',flush_before_ml:'',flush_after_ml:'',feed_start:localNow(),feed_end:'',feed_status:'completed',feed_fluid_mode:settings.fluidMode||'unsure',feed_tolerance:''});
 const [notes,setNotes]=useState(entry?.rawNotes||''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const saving=useRef(false);
 const set=(key,value)=>setData(d=>({...d,[key]:value}));
 const save=async status=>{if(saving.current)return;saving.current=true;setError('');try{const clean=normaliseFeed({...data,feed_status:status,item:data.feed_method==='flush'?'Water flush':data.item});setBusy(true);await onSave(clean,notes,entry);}catch(e){setError(e.message||'Could not save. Please try again.');}finally{saving.current=false;setBusy(false);}};
 return <div className="mt-4 space-y-4"><p className="text-sm text-slate-600">Record the care given using the person's existing feeding plan. Volumes are in ml; rates are recorded in ml/hour.</p>{error&&<p role="alert" className="rounded-xl bg-rose-50 p-3 text-rose-800">{error}</p>}<fieldset disabled={busy} className="min-w-0 space-y-4">
 {!entry&&presets.length>0&&<label className="block text-sm font-semibold">Use a recent feed as a starting point<select className={field} defaultValue="" onChange={e=>{const p=presets[Number(e.target.value)]?.rawData;if(p)setData(d=>({...d,item:p.item,feed_route:p.feed_route,feed_method:p.feed_method,feed_planned_ml:p.feed_planned_ml??'',feed_rate:p.feed_rate??''}));}}><option value="">New feed</option>{presets.map((p,i)=><option key={p.id} value={i}>{p.rawData.item} · {routeLabels[p.rawData.feed_route]}</option>)}</select></label>}
 <div className="grid gap-3 sm:grid-cols-2"><label className="block text-sm font-semibold">Route used<select className={field} value={data.feed_route} onChange={e=>set('feed_route',e.target.value)}>{Object.entries(routeLabels).filter(([k])=>k!=='combination').map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label className="block text-sm font-semibold">Method<select className={field} value={data.feed_method} onChange={e=>set('feed_method',e.target.value)}>{['bolus','pump','gravity','flush'].map(m=><option key={m} value={m}>{m==='flush'?'Water flush only':m[0].toUpperCase()+m.slice(1)}</option>)}</select></label></div>
 {data.feed_method!=='flush'&&<><label className="block text-sm font-semibold">Feed / formula<input className={field} value={data.item} maxLength={200} onChange={e=>set('item',e.target.value)}/></label><div className="grid gap-3 sm:grid-cols-2">{[['feed_planned_ml','Planned volume (optional)'],['feed_given_ml','Actually given (enter 0 if none)'],['feed_rate','Rate ml/hour (optional)']].map(([k,l])=><label className="block text-sm font-semibold" key={k}>{l}<input type="number" min="0" step="any" className={field} value={data[k]??''} onChange={e=>set(k,e.target.value)}/></label>)}</div></>}
 <div className="grid gap-3 sm:grid-cols-2">{[['feed_start','Start date and time'],['feed_end','End date and time (optional)']].map(([k,l])=><label className="block min-w-0 text-sm font-semibold" key={k}>{l}<input type="datetime-local" className={field} value={data[k]||''} onChange={e=>set(k,e.target.value)}/></label>)}{[['flush_before_ml',data.feed_method==='flush'?'Water given (ml)':'Water flush before (ml)'],['flush_after_ml','Water flush after (ml)']].map(([k,l])=><label className="block text-sm font-semibold" key={k}>{l}<input type="number" min="0" step="any" className={field} value={data[k]??''} onChange={e=>set(k,e.target.value)}/></label>)}</div>
 <label className="block text-sm font-semibold">Tolerance (optional)<select className={field} value={data.feed_tolerance||''} onChange={e=>set('feed_tolerance',e.target.value)}><option value="">Not recorded</option>{['Tolerated well','Discomfort','Nausea','Vomiting','Other'].map(t=><option key={t}>{t}</option>)}</select></label>
 <label className="block text-sm font-semibold">Notes<textarea className={field} rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></label>
 <p className="rounded-xl bg-sky-50 p-3 text-sm">Water flushes count towards fluids. Formula {data.feed_fluid_mode==='include'?'also counts by actual volume given':data.feed_fluid_mode==='unsure'?'does not count yet — choose a setting in the care profile':'is kept separate'}. Flushes should be recorded here only once. Volumes count on the start date.</p>
 <div className="flex flex-wrap gap-2"><button type="button" className="rounded-xl bg-teal-700 px-4 py-3 font-bold text-white" onClick={()=>save('completed')}>{busy?'Saving…':entry?(entry.rawData.feed_status==='active'?'Finish feed':'Save feed changes'):'Save completed feed'}</button>{data.feed_method!=='flush'&&canStart&&!entry&&<button type="button" className="rounded-xl border px-4 py-3 font-bold" onClick={()=>save('active')}>Start feed</button>}{entry&&<button type="button" className="rounded-xl border px-4 py-3" onClick={()=>save('stopped')}>Save as stopped early</button>}{onCancel&&<button type="button" className="rounded-xl border px-4 py-3" onClick={onCancel}>Cancel</button>}</div>
 {canStart&&!entry&&<p className="text-xs text-slate-500">Start feed records the start and any water already flushed. Finish it later to record the actual volume delivered.</p>}
 </fieldset></div>;
}
