import {schoolPlanForDay} from '../schoolSettings';
import {pickupConfirmationDue} from '../attendanceCalendar';
import {useState,useRef,useEffect} from 'react';
import {activeSchoolRecord} from '../attendance';
export default function SchoolSessionControls({entries=[],settings={},canStart,canEnd,onAction}){
 const [clock,setClock]=useState(()=>new Date()),[dismissed,setDismissed]=useState('');
 useEffect(()=>{const timer=setInterval(()=>setClock(new Date()),30000);return()=>clearInterval(timer);},[]);
 const [busy,setBusy]=useState(false),[error,setError]=useState('');const lock=useRef(false);
 const records=entries.filter(e=>e.rawData?.attendance).map(e=>({id:e.id.replace(/^care-/,''),data:e.rawData,entry:e}));
 const active=activeSchoolRecord(records);const now=new Date(),day=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;
 const plan=schoolPlanForDay(settings,day);
 const pickupDue=pickupConfirmationDue(active,settings,clock),promptKey=(active?.id||'')+':'+(plan?.pickup||'');
 const today=records.find(r=>r.entry.rawLogDate===day);const current=active||today;const recorded=!active&&today&&(today.data.schoolStartedAt||today.data.attendanceStatus!=='attended');
 return <section className="rounded-2xl border border-indigo-200 bg-indigo-50 p-4"><h3 className="font-bold">{active?'At School / Away':'School day'}</h3><p className="mt-1 text-sm text-slate-600">{active?'School session is running. Tap Picked Up/Home when they return.':'Only tap Left for School when they actually leave. Holidays and scheduled days never start this automatically.'}</p>{active&&<p className="mt-1 text-sm">Left {new Date(active.data.schoolStartedAt).toLocaleString('en-GB')}</p>}{settings.name&&<p className="mt-2 font-semibold">{settings.name}</p>}{plan&&<p className="mt-1 text-sm">{plan.departure?'Usual departure '+plan.departure:''}{plan.pickup?' · Planned pickup '+plan.pickup:''}</p>}{pickupDue&&dismissed!==promptKey&&<div role="status" className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm"><p className="font-bold">Have they been picked up?</p><p>The usual pickup time has passed. Confirm using Picked Up/Home below; the session will keep running until then.</p><button type="button" className="mt-2 font-semibold underline" onClick={()=>setDismissed(promptKey)}>Not yet</button></div>}{error&&<p role="alert" className="mt-2 text-sm text-rose-800">{error}</p>}<button type="button" disabled={busy||recorded||!(active?canEnd:canStart)} className="mt-3 rounded-xl bg-indigo-700 px-4 py-3 font-bold text-white disabled:opacity-50" onClick={async()=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await onAction({action:active?'end':'start',expectedLogId:current?.id||'',expectedUpdatedAt:current?.entry.rawUpdatedAt||null,timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone});}catch(e){setError(e.message||'Could not update school state.');}finally{lock.current=false;setBusy(false);}}}>{busy?'Saving…':active?'Picked Up/Home':recorded?'Attendance recorded':'Left for School'}</button></section>;
}
