import {schoolDays} from '../schoolSettings';
const labels={mon:'Monday',tue:'Tuesday',wed:'Wednesday',thu:'Thursday',fri:'Friday',sat:'Saturday',sun:'Sunday'};
const field='mt-1 block w-full min-w-0 rounded-xl border border-slate-300 bg-white p-3';
export default function SchoolSettings({value={},enabled,onEnabled,onChange}){
 const update=(day,patch)=>onChange({...value,days:{...value.days,[day]:{...value.days?.[day],...patch}}});
 return <section className="space-y-4 rounded-2xl border border-indigo-100 bg-indigo-50/50 p-4"><h3 className="text-lg font-bold">School / Nursery</h3><label className="flex items-center gap-3 text-sm font-semibold"><input type="checkbox" checked={enabled===true} onChange={e=>onEnabled(e.target.checked)}/>Show attendance for this profile</label><label className="block text-sm font-semibold">School / nursery name<input className={field} maxLength={150} value={value.name||''} onChange={e=>onChange({...value,name:e.target.value})}/></label><p className="text-sm text-slate-600">Choose usual days and optional departure and pickup times. These are planning times, not recorded attendance. Left for School and Back Home still control the live state.</p>
 {schoolDays.map(day=>{const row=value.days?.[day]||{};return <div key={day} className="rounded-xl border bg-white p-3"><label className="flex items-center gap-3 font-semibold"><input type="checkbox" checked={row.enabled===true} onChange={e=>update(day,{enabled:e.target.checked})}/>{labels[day]}</label>{row.enabled&&<div className="mt-3 grid grid-cols-2 gap-3"><label className="min-w-0 text-sm">Usual departure<input type="time" className={field} value={row.departure||''} onChange={e=>update(day,{departure:e.target.value})}/></label><label className="min-w-0 text-sm">Usual pickup<input type="time" className={field} value={row.pickup||''} onChange={e=>update(day,{pickup:e.target.value})}/></label></div>}</div>})}
 <p className="text-xs text-slate-600">Save care profile below to apply. Pickup appears on an active school widget for that day; holidays and weekends never start school automatically.</p></section>;
}
