import assert from 'node:assert/strict';
import { build } from 'esbuild';
const output=await build({entryPoints:['src/nativeWidgets.js'],bundle:true,write:false,format:'esm',plugins:[{name:'mock',setup(b){b.onResolve({filter:/api\/client$/},()=>({path:'api',namespace:'api-mock'}));b.onLoad({filter:/.*/,namespace:'api-mock'},()=>({contents:'export const api={issueWidgetAccess:async()=>({token:"test",expiresAt:new Date(Date.now()+604800000).toISOString()})};'}));b.onResolve({filter:/^@capacitor\/core$/},()=>({path:'core',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:'export const Capacitor={getPlatform:()=>"ios"}; export const registerPlugin=()=>({write:async ({json})=>{globalThis.widgetWrites.push(JSON.parse(json))},clear:async()=>{},connection:async()=>({installationId:"device"}),connect:async(value)=>{globalThis.widgetConnections.push(value)}});'}));}}]});
globalThis.widgetWrites=[]; globalThis.widgetConnections=[];
const {makeWidgetSnapshot,updateWidgets,clearWidgets}=await import('data:text/javascript;base64,'+Buffer.from(output.outputFiles[0].text).toString('base64'));
const now=new Date(2026,8,24,10,0);
const entry={section:'Toileting',summary:'Private detail',notes:'Secret notes',date:new Date(2026,8,24,9)};
const snapshot=makeWidgetSnapshot({id:'f:c',name:'Demo',entries:[entry],medicines:[{name:'Scheduled',dose:'2 ml',times:['09:00','11:00'],scheduleDays:['every_day']},{name:'PRN',times:['12:00'],scheduleDays:['prn']}],scheduled:()=>true,target:800,fluid:200,now,entryDate:e=>e.date});
assert.equal(snapshot.medicines[0].name,'Scheduled');
assert.equal(new Date(snapshot.medicines[0].timestamp*1000).getHours(),9, 'Outstanding dose stays after its scheduled time');
assert.equal(snapshot.medicines.length,4);
assert.equal(snapshot.care.toileting.label,'Toileting logged');
assert.equal(snapshot.fluid,200);
assert.ok(!JSON.stringify(snapshot).includes('Secret'));
assert.ok(!JSON.stringify(snapshot).includes('Private'));
console.log('PASS: outstanding scheduled times, PRN excluded, fluid totals, no care notes in shared snapshots');

await updateWidgets('user:family',snapshot,[{id:'f:c',name:'Demo'},{id:'f:other',name:'Other'}]);
assert.deepEqual(globalThis.widgetWrites.at(-1).children.map(c=>c.id),['f:c','f:other']);
assert.equal(globalThis.widgetWrites.at(-1).children[1].updated,0);
await updateWidgets('user:family',snapshot,[{id:'f:c',name:'Demo'}]);
assert.equal(globalThis.widgetWrites.at(-1).children.length,1);
await updateWidgets('other:family',{...snapshot,id:'new:c'},[{id:'new:c',name:'New'}]);
assert.deepEqual(globalThis.widgetWrites.at(-1).children.map(c=>c.id),['new:c']);
await clearWidgets();
console.log('PASS: all profiles selectable before sync, archived profiles removed, account isolation');
const sleepArgs = {id:'f:c',name:'Demo',medicines:[],scheduled:()=>true,target:0,fluid:0,now,entryDate:e=>e.date};
const sleeping = {section:'Sleep',rawCategory:'sleep',rawData:{bedtime:'09:00',wake_time:''},date:new Date(2026,8,24,9)};
assert.equal(makeWidgetSnapshot({...sleepArgs,entries:[sleeping]}).sleepingSince,sleeping.date.getTime()/1000);
assert.equal(makeWidgetSnapshot({...sleepArgs,entries:[{...sleeping,rawData:{...sleeping.rawData,wake_time:'09:30'}}]}).sleepingSince,null);
assert.equal(makeWidgetSnapshot({...sleepArgs,entries:[sleeping,{...sleeping,date:new Date(2026,8,24,9,30),rawData:{bedtime:'09:30',wake_time:'09:45'}}]}).sleepingSince,null);
assert.equal(makeWidgetSnapshot({...sleepArgs,entries:[{...sleeping,date:new Date(2026,8,25,9)}]}).sleepingSince,null);
assert.equal(makeWidgetSnapshot({...sleepArgs,entries:[]}).sleepingSince,null);
console.log('PASS: active sleep, waking, newer completed sleep, future logs and empty profiles');

const sleepSettings = makeWidgetSnapshot({...sleepArgs,usualBedtime:'20:00',entries:[{...sleeping,id:'care-123'}]});
assert.equal(sleepSettings.usualBedtime,'20:00');
assert.equal(sleepSettings.sleepLogId,'123');
assert.equal(makeWidgetSnapshot({...sleepArgs,entries:[]}).usualBedtime,null);
console.log('PASS: optional bedtime and sleep state reference');
